---
- name: Restart zookeeper
  #shell: service zookeeper restart
  #sudo: yes
  service:
    name: zookeeper
    state: restarted

# - name: Start mesos-master
#   #shell: service mesos-master start
#   #sudo: yes
#   service:
#     name: mesos-master
#     state: started
#
# - name: Stop mesos-master
#   #shell: service mesos-master stop
#   #sudo: yes
#   service:
#     name: mesos-master
#     state: stopped

- name: Restart mesos-master
  service:
    name: mesos-master
    state: restarted

# - name: Start mesos-slave
#   #shell: service mesos-slave start
#   #sudo: yes
#   service:
#     name: mesos-slave
#     state: started
#
# - name: Stop mesos-slave
#   #shell: service mesos-slave stop
#   #sudo: yes
#   service:
#     name: mesos-slave
#     state: stopped

- name: Start marathon
  #shell: service marathon start
  #sudo: yes
  service:
    name: marathon
    state: started

# - name: Stop marathon
#   #shell: service marathon stop
#   #sudo: yes
#   service:
#     name: marathon
#     state: stopped


# - name: Restart mesos-slave
#   service:
#     name: mesos-slave
#     state: restarted

# - name: Stop zookeeper
#   #shell: service zookeeper stop
#   #sudo: yes
#   service:
#     name: zookeeper
#     state: stopped
