---
# - name: ensure repository key is installed
#   apt_key:
#     id: "58118E89F3A912897C070ADBF76221572C52609D"
#     keyserver: "hkp://p80.pool.sks-keyservers.net:80"
#     state: present
#
# - name: ensure docker registry is available
#   # For Ubuntu 14.04 LTS, use this repository:
#   apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present
#   # For Ubuntu 16.04 LTS, use this repo instead:
#   # apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present
#
# - name: ensure docker and dependencies are installed
#   apt: name=docker-engine update_cache=yes

- name: Add debian jessie-backports repository
  apt_repository:
    repo="deb http://http.debian.net/debian jessie-backports main"
    state=present
  tags: install

- name: Update APT
  apt: update_cache=yes
  tags: install

- name: Install docker
  apt:
    pkg=docker.io
    state=present
  tags: install

- name: Enable Docker service
  service:
    name=docker
    enabled=yes
    state=started
  tags: service

# Uncomment the following to enable insecure registries with Docker
#- name: ensure docker can use insecure registries in 10.11.0.0/16
#  lineinfile: "dest=/etc/default/docker regexp=^DOCKER_OPTS line=DOCKER_OPTS='--insecure-registry 10.11.0.0/16'"

- name: add vagrant to docker group
  user:
    name: vagrant
    groups: docker
    append: yes

# - name: restart docker service
#   service:
#     name=docker
#     state=restarted
